"""initial schema

Revision ID: e8cbd521caa4
Revises: 
Create Date: 2026-09-30 22:50:39.053443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cbd521caa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clock_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offset_seconds', sa.Integer(), nullable=False),
    sa.Column('last_advance_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('scope_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('last_auto_contact_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('reply_token', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reply_token')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('import_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name')
    )
    with op.batch_alter_table('import_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_lists_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('upload_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('upload_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_tokens_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_tokens_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_list_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('blob', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_list_id'], ['import_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_import_list_id'), ['import_list_id'], unique=False)

    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_blob', sa.String(length=80), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('from_name', sa.String(length=300), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.Column('message_id', sa.String(length=300), nullable=True),
    sa.Column('in_reply_to', sa.String(length=300), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=True),
    sa.Column('match_notes', sa.JSON(), nullable=False),
    sa.Column('suggested_conversation_ids', sa.JSON(), nullable=False),
    sa.Column('sender_is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('import_list_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('backup_email', sa.String(length=320), nullable=True),
    sa.Column('ownership_mode', sa.String(length=10), nullable=False),
    sa.Column('cc_requester', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('auto_contact_count', sa.Integer(), nullable=False),
    sa.Column('followup_due_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('overdue_sent_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('handed_back_at', sa.DateTime(), nullable=True),
    sa.Column('handback_reason', sa.String(length=60), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('needs_recheck', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['checklist_versions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['import_list_id'], ['import_lists.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('actor_detail', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('checklist_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'number')
    )
    with op.batch_alter_table('checklist_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_versions_request_id'), ['request_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_request_id'), ['request_id'], unique=False)

    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('blob', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('detected_type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('parent_file_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('unreadable_reason', sa.Text(), nullable=True),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_id'], ['inbound_messages.id'], ),
    sa.ForeignKeyConstraint(['parent_file_id'], ['evidence_files.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_files_inbound_id'), ['inbound_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('merged_into', sa.String(length=100), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('ownership_mode', sa.String(length=10), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_batch_id'), ['batch_id'], unique=False)

    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('from_name', sa.String(length=300), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('to', sa.JSON(), nullable=False),
    sa.Column('cc', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=400), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('in_reply_to', sa.String(length=300), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=300), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('request_ids', sa.JSON(), nullable=False),
    sa.Column('counted_request_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('provider_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inbound_id'], ['inbound_messages.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_questions_request_id'), ['request_id'], unique=False)

    op.create_table('request_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'depends_on_id')
    )
    with op.batch_alter_table('request_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_dependencies_depends_on_id'), ['depends_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_dependencies_request_id'), ['request_id'], unique=False)

    op.create_table('request_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'provider_id')
    )
    with op.batch_alter_table('request_owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_owners_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_owners_request_id'), ['request_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('subpoints', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['checklist_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_version_id'), ['version_id'], unique=False)

    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('suspicious', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['checklist_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checks_request_id'), ['request_id'], unique=False)

    op.create_table('conversation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['checklist_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'request_id')
    )
    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_requests_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_requests_request_id'), ['request_id'], unique=False)

    op.create_table('evidence_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['evidence_files.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'request_id')
    )
    with op.batch_alter_table('evidence_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_assignments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_assignments_request_id'), ['request_id'], unique=False)

    op.create_table('verdict_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['checklist_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verdict_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdict_overrides_request_id'), ['request_id'], unique=False)

    op.create_table('item_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('model_verdict', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('subpoints', sa.JSON(), nullable=False),
    sa.Column('review_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_verdicts_check_id'), ['check_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_verdicts_check_id'))

    op.drop_table('item_verdicts')
    with op.batch_alter_table('verdict_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdict_overrides_request_id'))

    op.drop_table('verdict_overrides')
    with op.batch_alter_table('evidence_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_assignments_request_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_assignments_file_id'))

    op.drop_table('evidence_assignments')
    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_requests_request_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_requests_conversation_id'))

    op.drop_table('conversation_requests')
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checks_request_id'))

    op.drop_table('checks')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_version_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('request_owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_owners_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_owners_provider_id'))

    op.drop_table('request_owners')
    with op.batch_alter_table('request_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_dependencies_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_dependencies_depends_on_id'))

    op.drop_table('request_dependencies')
    with op.batch_alter_table('provider_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_questions_request_id'))

    op.drop_table('provider_questions')
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_request_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_conversation_id'))

    op.drop_table('outbound_messages')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_batch_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_files_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_inbound_id'))

    op.drop_table('evidence_files')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_request_id'))

    op.drop_table('comments')
    with op.batch_alter_table('checklist_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_versions_request_id'))

    op.drop_table('checklist_versions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_requests_state'))

    op.drop_table('requests')
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_conversation_id'))

    op.drop_table('inbound_messages')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_import_list_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('upload_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_tokens_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_upload_tokens_provider_id'))

    op.drop_table('upload_tokens')
    with op.batch_alter_table('import_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_lists_workspace_id'))

    op.drop_table('import_lists')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_provider_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_workspace_id'))

    op.drop_table('users')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_workspace_id'))

    op.drop_table('providers')
    op.drop_table('workspaces')
    op.drop_table('scope_cache')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_workspace_id'))

    op.drop_table('events')
    op.drop_table('clock_state')
    # ### end Alembic commands ###
